API_TOKEN = '1671620851:AAHOuyZP6sAZ1z_bT5FQYWhauiVLcCAFsrw'
WEBHOOK_HOST = '4roonas.ru'
WEBAPP_PORT = 8080
admins = []

PG_USER = ''
PG_HOST = ''
PG_PASSWORD = ''
PG_DATABASE = ''
database_uri = f'postgres://{PG_USER}:{PG_PASSWORD}@{PG_HOST}/{PG_DATABASE}'

WEBHOOK_PATH = f'/bots/{API_TOKEN}/{WEBAPP_PORT}'



